[sources.postgres.credentials]
drivername = "drivername"
database = "database"
password = "password"
username = "username"
host = "host"
port = 0

[destination.snowflake.credentials]
database = "database"
password = "password"
username = "username"
host = "host"
warehouse = "warehouse"
role = "role"
